// Generated by gencpp from file erick/mensaje01Roger.msg
// DO NOT EDIT!


#ifndef ERICK_MESSAGE_MENSAJE01ROGER_H
#define ERICK_MESSAGE_MENSAJE01ROGER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace erick
{
template <class ContainerAllocator>
struct mensaje01Roger_
{
  typedef mensaje01Roger_<ContainerAllocator> Type;

  mensaje01Roger_()
    : mensaje()  {
    }
  mensaje01Roger_(const ContainerAllocator& _alloc)
    : mensaje(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mensaje_type;
  _mensaje_type mensaje;





  typedef boost::shared_ptr< ::erick::mensaje01Roger_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::erick::mensaje01Roger_<ContainerAllocator> const> ConstPtr;

}; // struct mensaje01Roger_

typedef ::erick::mensaje01Roger_<std::allocator<void> > mensaje01Roger;

typedef boost::shared_ptr< ::erick::mensaje01Roger > mensaje01RogerPtr;
typedef boost::shared_ptr< ::erick::mensaje01Roger const> mensaje01RogerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::erick::mensaje01Roger_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::erick::mensaje01Roger_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::erick::mensaje01Roger_<ContainerAllocator1> & lhs, const ::erick::mensaje01Roger_<ContainerAllocator2> & rhs)
{
  return lhs.mensaje == rhs.mensaje;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::erick::mensaje01Roger_<ContainerAllocator1> & lhs, const ::erick::mensaje01Roger_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace erick

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::erick::mensaje01Roger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erick::mensaje01Roger_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erick::mensaje01Roger_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erick::mensaje01Roger_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erick::mensaje01Roger_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erick::mensaje01Roger_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::erick::mensaje01Roger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a903682ef166367b021ed012ebf97f5";
  }

  static const char* value(const ::erick::mensaje01Roger_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a903682ef166367ULL;
  static const uint64_t static_value2 = 0xb021ed012ebf97f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::erick::mensaje01Roger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "erick/mensaje01Roger";
  }

  static const char* value(const ::erick::mensaje01Roger_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::erick::mensaje01Roger_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mensaje\n"
;
  }

  static const char* value(const ::erick::mensaje01Roger_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::erick::mensaje01Roger_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mensaje);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mensaje01Roger_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::erick::mensaje01Roger_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::erick::mensaje01Roger_<ContainerAllocator>& v)
  {
    s << indent << "mensaje: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mensaje);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERICK_MESSAGE_MENSAJE01ROGER_H
