// Generated by gencpp from file erick/servCuadradoRequest.msg
// DO NOT EDIT!


#ifndef ERICK_MESSAGE_SERVCUADRADOREQUEST_H
#define ERICK_MESSAGE_SERVCUADRADOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace erick
{
template <class ContainerAllocator>
struct servCuadradoRequest_
{
  typedef servCuadradoRequest_<ContainerAllocator> Type;

  servCuadradoRequest_()
    : numero(0.0)  {
    }
  servCuadradoRequest_(const ContainerAllocator& _alloc)
    : numero(0.0)  {
  (void)_alloc;
    }



   typedef double _numero_type;
  _numero_type numero;





  typedef boost::shared_ptr< ::erick::servCuadradoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::erick::servCuadradoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct servCuadradoRequest_

typedef ::erick::servCuadradoRequest_<std::allocator<void> > servCuadradoRequest;

typedef boost::shared_ptr< ::erick::servCuadradoRequest > servCuadradoRequestPtr;
typedef boost::shared_ptr< ::erick::servCuadradoRequest const> servCuadradoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::erick::servCuadradoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::erick::servCuadradoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::erick::servCuadradoRequest_<ContainerAllocator1> & lhs, const ::erick::servCuadradoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.numero == rhs.numero;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::erick::servCuadradoRequest_<ContainerAllocator1> & lhs, const ::erick::servCuadradoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace erick

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::erick::servCuadradoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erick::servCuadradoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erick::servCuadradoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erick::servCuadradoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erick::servCuadradoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erick::servCuadradoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::erick::servCuadradoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d9200d7ba2bbf6427fa65ce059ca943";
  }

  static const char* value(const ::erick::servCuadradoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d9200d7ba2bbf64ULL;
  static const uint64_t static_value2 = 0x27fa65ce059ca943ULL;
};

template<class ContainerAllocator>
struct DataType< ::erick::servCuadradoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "erick/servCuadradoRequest";
  }

  static const char* value(const ::erick::servCuadradoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::erick::servCuadradoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Archivo de mensaje para servicio de calculo del cuadrado\n"
"float64 numero 	            # Campo para mensaje de peticion\n"
;
  }

  static const char* value(const ::erick::servCuadradoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::erick::servCuadradoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numero);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servCuadradoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::erick::servCuadradoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::erick::servCuadradoRequest_<ContainerAllocator>& v)
  {
    s << indent << "numero: ";
    Printer<double>::stream(s, indent + "  ", v.numero);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERICK_MESSAGE_SERVCUADRADOREQUEST_H
