// Generated by gencpp from file erick/servCuadrado.msg
// DO NOT EDIT!


#ifndef ERICK_MESSAGE_SERVCUADRADO_H
#define ERICK_MESSAGE_SERVCUADRADO_H

#include <ros/service_traits.h>


#include <erick/servCuadradoRequest.h>
#include <erick/servCuadradoResponse.h>


namespace erick
{

struct servCuadrado
{

typedef servCuadradoRequest Request;
typedef servCuadradoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct servCuadrado
} // namespace erick


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::erick::servCuadrado > {
  static const char* value()
  {
    return "34f2e5caf0038897a998616af4afa87b";
  }

  static const char* value(const ::erick::servCuadrado&) { return value(); }
};

template<>
struct DataType< ::erick::servCuadrado > {
  static const char* value()
  {
    return "erick/servCuadrado";
  }

  static const char* value(const ::erick::servCuadrado&) { return value(); }
};


// service_traits::MD5Sum< ::erick::servCuadradoRequest> should match
// service_traits::MD5Sum< ::erick::servCuadrado >
template<>
struct MD5Sum< ::erick::servCuadradoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::erick::servCuadrado >::value();
  }
  static const char* value(const ::erick::servCuadradoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::erick::servCuadradoRequest> should match
// service_traits::DataType< ::erick::servCuadrado >
template<>
struct DataType< ::erick::servCuadradoRequest>
{
  static const char* value()
  {
    return DataType< ::erick::servCuadrado >::value();
  }
  static const char* value(const ::erick::servCuadradoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::erick::servCuadradoResponse> should match
// service_traits::MD5Sum< ::erick::servCuadrado >
template<>
struct MD5Sum< ::erick::servCuadradoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::erick::servCuadrado >::value();
  }
  static const char* value(const ::erick::servCuadradoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::erick::servCuadradoResponse> should match
// service_traits::DataType< ::erick::servCuadrado >
template<>
struct DataType< ::erick::servCuadradoResponse>
{
  static const char* value()
  {
    return DataType< ::erick::servCuadrado >::value();
  }
  static const char* value(const ::erick::servCuadradoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ERICK_MESSAGE_SERVCUADRADO_H
